package by.bsu.travelagency.entity.enumeration;

public enum TourType {
    ECOTOURISM_HOLIDAYS,
    WILDLIFE_AND_NATURE_HOLIDAYS,
    AFRICAN_SAFARI_HOLIDAYS,
    WELLNESS_AND_SPA_HOLIDAY,
    CRUISE_HOLIDAYS,
    WALKING_AND_ACTIVE_HOLIDAYS,
    CULTURAL_HOLIDAYS,
    GROUP_HOLIDAYS,
    LUXURY_BEACH_HOLIDAYS,
    THE_WEEKEND_BREAK
}
